# RUN ME WITH ruby counter.rb
# Sund one!

system("say this is an announcement for starting the countdown until presentation start")
sleep(1)
system("say get ready!!")
sleep(1)
system("say 30 minutes before presentations")
sleep(12*30)
system("say 5 minutes until presentation")
sleep(5*30)
system("say presentation ready to start, rent-a tour you are first")
system("say 10")
sleep(1)
system("say 9")
sleep(1)
system("say 8")
sleep(1)
system("say 7")
sleep(1)
system("say 6")
sleep(1)
system("say 5")
sleep(1)
system("say 4")
sleep(1)
system("say 3")
sleep(1)
system("say 2")
sleep(1)
system("say 1")
sleep(1)
system("say Ignition!")

